try:
  print(2 / 0)
except:
 print('une erreur est survenue')
